spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
            client-secret: kq6zIo0myJotHK5_0irhtYnW
          facebook:
            client-id: 465358593799840
            client-secret: a37286e3dae00dcdce628f40dfe363f5
custom:
  oauth2:
    kakao:
      client-id: 1b8ff676ae01724ed77437f98d399543


#spring:
#  h2:
#    console:
#      enabled: true
# ddl-auto 설정이 안먹힘 오류발생

#server:
#  port: 8080
#  tomcat:
#    uri-encoding: UTF-8
#
#spring:
#  profiles:
#    active: local # 기본 환경 선택
#
## local 환경
#---
#spring:
#  profiles: local
#  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true